name: Generate list

on:
  workflow_dispatch:
    inputs:
      rtag:
        description: 'uazo/bromite-remote-index TAG'
        required: true
        default: ''

env:
  RTAG: ${{ github.event.inputs.rtag }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: bromite-flags-list
          fetch-depth: 1
          
      - name: Prepare container
        run: |
          sudo apt update
          sudo apt install -y wget unzip sqlite3
          wget https://github.com/uazo/ClangQL/releases/download/v0.3/ClangQL.zip
          unzip ClangQL.zip
          rm ClangQL.zip
          
          sqlite3 --version
          docker run -d -p 50051:50051 uazo/bromite-remote-index:$RTAG
          sleep 1m
          sqlite3 <bromite-flags-list/extract.txt >output.txt

      - name: Publish
        uses: actions/upload-artifact@v2
        with:
          name: output.txt
          path: output.txt
          
