name: Generate list

on:
  workflow_dispatch:
    inputs:
      rtag:
        description: 'uazo/bromite-remote-index TAG'
        required: true
        default: ''

      index_url:
        description: 'full url of idex'
        required: true
        default: ''

env:
  RTAG: ${{ github.event.inputs.rtag }}
  INDEX_URL: ${{ github.event.inputs.index_url }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: bromite-flags-list
          fetch-depth: 1
          
      - name: Prepare container
        run: |
          sudo apt update
          sudo apt install -y wget unzip sqlite3
          wget https://github.com/uazo/ClangQL/releases/download/v0.3/ClangQL.zip
          unzip ClangQL.zip
          rm ClangQL.zip
          
          sqlite3 --version

          # docker run -d -p 50051:50051 uazo/bromite-remote-index:$RTAG
          sudo apt install -y cron python3 python3-requests nginx-light
          
          sudo apt install -y --no-install-recommends python3-pip && \
            pip3 install j2cli --break-system-packages && \
            sudo apt remove -y python3-pip && \
            sudo apt autoremove -y
          
          sudo rm -rf /var/www/html/*

          wget https://github.com/clangd/clangd/releases/download/snapshot_20260222/clangd_indexing_tools-linux-snapshot_20260222.zip && \
            unzip clangd_indexing_tools-linux-snapshot_20260222.zip && \
            rm clangd_indexing_tools-linux-snapshot_20260222.zip

          wget -O index.zip $INDEX_URL
          unzip index.zip

      - name: Generate output.txt
        run: |
          IDX=$(echo *.idx)

          ./snapshot_20260222/bin/clangd-index-server \
            $IDX \
            /chromium/src \
            --server-address="0.0.0.0:50051" \
            --limit-results=99999999999 \
            >/dev/null 2>&1 &

          sleep 5m
          sqlite3 -separator '=%=' <bromite-flags-list/extract.txt >output.txt

      - name: Publish
        uses: actions/upload-artifact@v4
        with:
          name: output.txt
          path: output.txt
          
      - name: Generate
        run: |
          wget https://github.com/uazo/superpatch/releases/latest/download/SuperPatchUtils.tar.gz
          tar xfz SuperPatchUtils.tar.gz
          bin/SuperPatchUtils parse-flags $RTAG output.txt out
          mv output.txt out
          tar czvf output.tar.gz out

      - name: Publish
        uses: actions/upload-artifact@v4
        with:
          name: output.tar.gz
          path: output.tar.gz
